authentik:
  error_reporting:
    enabled: false

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - authentik.cluster.zachsampson.dev
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: true
      nginx.ingress.kubernetes.io/proxy-ssl-verify: off
      nginx.ingress.kubernetes.io/x-forwarded-proto: https
  environment:
    - name: AUTHENTIK_HOST
      value: https://authentik.cluster.zachsampson.dev
    - name: EXTERNAL_URL
      value: https://authentik.cluster.zachsampson.dev

postgresql:
  enabled: true

redis:
  enabled: true
