authentik:
  error_reporting:
    enabled: false

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - authentik.cluster.zachsampson.dev

postgresql:
  enabled: true

redis:
  enabled: true
