authentik:
  secret_key: "PleaseGenerateASecureKey"
  error_reporting:
    enabled: true
  postgresql:
    password: "ThisIsNotASecurePassword"

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - authentik.cluster.zachsampson.dev

postgresql:
  enabled: true

redis:
  enabled: true
