server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
    hosts:
      - "auth.zachsampson.dev"
    paths:
      - path: /
        pathType: Prefix
    tls:
      - hosts:
          - "auth.zachsampson.dev"
        secretName: authentik-tls
