name: Setup kubeconfig
description: Sets up a .kube/config file for the specified DigitalOcean cluster

inputs:
  cluster-name:
    description: Name of the cluster to create kubeconfig for
    required: true
    default: main
  digitalocean-token:
    description: The token to authenticate to digital ocean with
    required: true

runs:
  using: composite
  steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.digitalocean-token }}

    - name: Install Kubectl
      uses: azure/setup-kubectl@v3

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Save kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ inputs.cluster-name }}
      shell: bash
