name: Create K8s Cluster on DigitalOcean

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - ../../terraform/**
      - .github/workflows/cluster.yml
  push:
    branches: [ main ]
    paths:
      - ../../terraform/**
      - .github/workflows/cluster.yml

env:
  CLUSTER_NAME: main

jobs:
  cluster:
    uses: ./.github/workflows/tf-plan-and-apply.yaml
    with:
      apply: false
      working-directory: ./cluster
      cluster-name: main
    secrets: inherit