name: Initialize K8s Cluster on DigitalOcean

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        type: string
        required: false
        description: Name of the K8s cluster
        default: main
  pull_request:
    branches: [ main ]
    paths:
      - init-cluster/**
      - .github/workflows/init-cluster.yml
  push:
    branches: [ main ]
    paths:
      - init-cluster/**
      - .github/workflows/init-cluster.yml

jobs:
  terraform:
    name: Run the Terraform Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./init-cluster
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: tf-plan
        run: |
          terraform plan -no-color -input=false \
            -var digitalocean_token=${{ secrets.DIGITALOCEAN_TOKEN }} \
            -var cluster_name=${{ inputs.cluster-name || 'main' }}

      - name: Output Plan Summary
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          echo "# :gear: Init Cluster :gear:" >> $GITHUB_STEP_SUMMARY
          echo "## :book: Terraform Plan" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`${{ steps.tf-plan.outputs.stdout }}\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Terraform Apply
        id: tf-apply
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          terraform apply -auto-approve -no-color -input=false \
            -var digitalocean_token=${{ secrets.DIGITALOCEAN_TOKEN }} \
            -var cluster_name=${{ inputs.cluster-name }}

      - name: Output Apply Summary
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "## :shipit: Terraform Apply" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`${{ steps.tf-apply.outputs.stdout }}\`\`\`" >> $GITHUB_STEP_SUMMARY
