name: Setup Monitoring Tools

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        type: string
        description: The cluster to setup monitoring tools for
        required: true
        default: main
  workflow_call:
    inputs:
      cluster-name:
        type: string
        description: The cluster to setup monitoring tools for
        required: true

jobs:
  monitoring:
    name: Deploy Monitoring Stack
    runs-on: ubuntu-latest
    concurrency: ${{ github.repository }}-${{ inputs.cluster-name }}-monitoring
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/kubeconfig
        with:
          cluster-name: ${{ inputs.cluster-name }}
          digitalocean-token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Add helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Install monitoring stack
        run: |
          helm upgrade --install monitoring ./monitoring \
            --namespace monitoring --create-namespace
