name: Setup Monitoring Tools

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        type: string
        description: The name of the K8s cluster to setup ingress for
        required: true
        default: main
  workflow_call:
    inputs:
      cluster-name:
        type: string
        description: The cluster to setup monitoring tools for
        required: true

jobs:
  grafana:
    name: Deploy Grafana
    runs-on: ubuntu-latest
    concurrency: ${{ github.repository }}-${{ inputs.cluster-name }}-monitoring
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/kubeconfig
        with:
          cluster-name: ${{ inputs.cluster-name }}
          digitalocean-token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Add helm repositories
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: Install grafana
        run: |
          helm upgrade --install grafana grafana/grafana \ 
            --namespace monitoring --create-namespace \
            --values ./resources/monitoring/values.yaml
