name: Test Deploy Docker

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      values-file: ./resources/hello-world/values.yaml
      release-name: hello-world
      namespace: hello-world
      cluster-name: main
    secrets: inherit